# Blog settings
permalink: /projects/:title


# My variables
name: sgelb
description: projects and stuff
github: https://github.com/sgelb


include: ["_pages", "mapline"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
